### ISSUE TITLE
"ps-list/vendor/fastlist-0.2.1-x86.exe" flagged as Trojan by BitDefender

### ISSUE THREAD

**Issue by fabiendem** [sindresorhus/ps-list#42]
Hi,

We have tried installing yarn packages depending on `ps-list`.
At install time we have been getting errors (permission denied to copy the file `fastlist-0.2.1-x86.exe`), and quickly realised it was flagged by BitDefender as a Trojan ☠️  on our machines.

Here is the report:
```
04/06/2020, 10:35
 
Trojan.GenericKD.33959353 deleted
 
/[REDACTED]/Library/Caches/Yarn/v6/npm-ps-list-7.1.0-f134c78fce689da1f243a28d1dd0bf438569c151-integrity/node_modules/ps-list/vendor/fastlist-0.2.1-x86.exe
```

If I download directly the file `fastlist-0.2.1-x86.exe` from `https://github.com/sindresorhus/ps-list/tree/master/vendor`, it gets flagged as well.

Do you know if this is a false positive or is something wrong with this file?

Cheers!

**Comment by MarkTiedemann** [comment]
Hi @fabiendem,

I built https://github.com/MarkTiedemann/fastlist. This looks like a false positive to me, based on the description I found here: https://www.f-secure.com/v-descs/trojan_generickd_2427119.shtml

> This malware (SHA1: e81a329b75e962ebef17faf72f2b7d4d0f391589) is distributed from a malicious website in a ZIP file with the filename 'DHL_Report_[string of numbers].zip'. The ZIP file appears to contain a PDF document, as the file uses the PDF file format icon.
Execution

> On extraction, the file contained in the ZIP file turns out to be an executable program. When this file is executed, it appears to be damaged and displays an error message:

> In the background however, the program injects code into running processes (including explorer.exe).

> It also silently attempts to connect to remote servers (mainly located in the United States, United Kingdom and Japan).

I don't know why the false positive exists. I suspect that the trojan is also calling the Windows APIs to get a list of the running processes.

In any case, being falsely flagged by anti-virus software is obviously pretty bad.

@sindresorhus I think you should probably revert to v7.0.0, e.g. downgrade fastlist again to v0.1.0 (instead of v0.2.1).

I'm sorry for any inconvience that this may have caused.

**Comment by fabiendem** [comment]
Hey @MarkTiedemann 
No probs, thanks for the prompt reply.

Am wondering how you found https://www.f-secure.com/v-descs/trojan_generickd_2427119.shtml ?

I am asking because the name/alias `Trojan.GenericKD.2427119` in there doesn't match with the one reported on our machine `Trojan.GenericKD.33959353` (see snippet in first message).

I will keep an eye on this thread

**Comment by MarkTiedemann** [comment]
Damn. You are right. I just clicked the first link on Google... I didn't notice the tiny "Missing: 33959353" part.

**Comment by MarkTiedemann** [comment]
Just uploaded it to VirusTotal: https://www.virustotal.com/gui/file/11f851ecb1dac37956832245dbed78b5aa9ecd985450777d19659c73469c9ebb/detection

Here's the report: https://vtbehaviour.commondatastorage.googleapis.com/11f851ecb1dac37956832245dbed78b5aa9ecd985450777d19659c73469c9ebb_VirusTotal%20Jujubox.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1591273561&Signature=XAg1GTdVRH4xyIG6%2BsJf0l8I9Ht7ua5BbZGeF0AafsMl926RB4h%2Fa%2FcwwIa2MGlZCP63VmyhhDqb%0AvT43hscKLDY4%2Bgr4crUTiymYVujpZnk4%2BrdQ5saP6YEynQeZz3W8V1l0nix5uXckH9KW%2BqL6PiAP%0AyxPrYEvQ%2FMvxQQTixno%3D&response-content-type=text%2Fhtml;

I highlighted some calls and where they originate in the source:

`{"lpProcName":"CreateToolhelp32Snapshot","hModule":"kernel32.dll"}`
https://github.com/MarkTiedemann/fastlist/blob/master/fastlist.cpp#L13

`{"lpProcName":"Process32FirstW","hModule":"kernel32.dll"}`
https://github.com/MarkTiedemann/fastlist/blob/master/fastlist.cpp#L22

`{"lpProcName":"Process32NextW","hModule":"kernel32.dll"}`
https://github.com/MarkTiedemann/fastlist/blob/master/fastlist.cpp#L32

Again, this is a false positive. But I'm not sure how to "unflag" it.

**Comment by MarkTiedemann** [comment]
On another note, faslist v0.1.0 is also flagged as a potential virus by 1 AV software:

https://www.virustotal.com/gui/file/071f43816861b30663b17649abfcca743f17b353786218bac1f0f92e55acb3d8/detection

The full report says:

```

SHA256:    | 071f43816861b30663b17649abfcca743f17b353786218bac1f0f92e55acb3d8
File type: | EXE
Copyright: |  
Version:   |  
Shell or compiler: | COMPILER:Microsoft Visual Studio .NET 2005 -- 2008 -> Microsoft Corporation *

Behaviour:   | Enumerate process
Detail info: | N/A

Behaviour:   | Output to console
Detail info: | N/A
```

If your program can get flagged for "enumerating processes" and "output to the console", I'm not sure what we can do to fix this...

**Comment by sindresorhus** [comment]
I've seen this a lot. This is honestly not our problem. Antivirus apps are malware themselves, as they are [extremely insecure](https://www.techzine.eu/news/security/45677/trend-micro-zero-days-abused-by-hackers/), and often make the situation worse. I would recommend reporting this as a false-positive to BitDefender.

**Comment by fabiendem** [comment]
Alright cheers all, @MarkTiedemann if you have the time, it can reported as false positive here: https://www.bitdefender.com/submit/
If we don't have any news we may do an attempt on our side or find alternatives.

FYI we are seeing this because `ps-list` is a dep of a dep for [Appium iOS](https://appium.io/)

**Comment by MarkTiedemann** [comment]
> Alright cheers all, @MarkTiedemann if you have the time, it can reported as false positive here: https://www.bitdefender.com/submit/

Thanks, I will submit the false positive later today.

> If we don't have any news we may do an attempt on our side or find alternatives.

As mentioned earlier, a temporary fix would be to use ps-list v7.0.0, which ships with fastlist v0.1.0, which is not flagged as a virus, at least not by BitDefender. (I'm not sure whether you can patch Appium third-party dependencies, though.)

**Comment by MarkTiedemann** [comment]
I found another "virus report" by Joe Sandbox: https://www.joesandbox.com/analysis/235045/0/html

According to the report, there a 3 reasons why fastlist is (falsely) classified as malware:
1) In the category "Execution" it is flagged for "Execution through API", specifically "Process monitoring", which, of course, is kind of the whole point of fastlist...
2) In the category "Defense Evasion" it is flagged for "Software Packing" and "Obfuscated Files or Information", which stems from me using [UPX](https://github.com/upx/upx) to [pack](https://github.com/MarkTiedemann/fastlist/blob/master/pack.cmd) the binary for a smaller download size
3) In the category "Discovery" it is flagged for "Security Software Discovery" (because the security software is also just a running process on the computer) and "System Information Discovery", such as, again, "Process monitoring"

There's even a video in the report showing fastlist working just fine. :)

![Capture](https://user-images.githubusercontent.com/7062160/83807146-e5eb1600-a6b2-11ea-9916-8cf5e963f747.PNG)

**Comment by MarkTiedemann** [comment]
@fabiendem I have submitted fastlist as a false positive at BitDefender. I hope this will fix your installation soon. :)

 For anyone else reading this who is not using BitDefender: There are 6 other anti-virus tools which I would also need to submit the false positive to. I may do this in the following days, but please understand that progress may be slow.

**Comment by fabiendem** [comment]
Thank you @MarkTiedemann 👍 

We have been able to add it to the Allowed list in our config until BitDefender does it for good for everyone.

Btw there is a short Reddit thread as well 😄 : https://www.reddit.com/r/javascript/comments/f0kmqd/askjs_fastlistexe_was_flagged_as_a_malware_by_my/

**Comment by MarkTiedemann** [comment]
Haha, yeah, I know that thread. When I first saw it, I found it funny and even put it in the readme: "_Reddit rumors to the contrary notwithstanding, it is not a virus._" (https://github.com/MarkTiedemann/fastlist#notes)

But this is too many false positive reports to be funny anymore...
